FROM python:3.8-slim
EXPOSE 8080
WORKDIR /app

# Define environment variables
ENV CELERY_BROKER_URL=redis://redis:6379/0
ENV CELERY_RESULT_BACKEND=redis://redis:6379/0

COPY api-requirements.txt .

RUN pip install --no-cache-dir -r api-requirements.txt

COPY . .

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]

